export const fakeData = [
  {
    id: 1,
    title: "Osh",
    price: 20000,
    icon: "food.svg",
    count: 0,
    description: "Juda mazali",
  },
  {
    id: 2,
    title: "Fries",
    price: 18000,
    icon: "food.svg",
    count: 0,
    description: "Juda mazali",
  },
  {
    id: 3,
    title: "Hotdog",
    price: 22000,
    icon: "food.svg",
    count: 0,
    description: "Juda mazali",
  },
  {
    id: 4,
    title: "Taco",
    price: 22000,
    icon: "food.svg",
    count: 0,
    description: "Juda mazali",
  },
  {
    id: 5,
    title: "Pizza",
    price: 24000,
    icon: "food.svg",
    count: 0,
    description: "Juda mazali",
  },
  {
    id: 6,
    title: "Donut",
    price: 15000,
    icon: "food.svg",
    count: 0,
    description: "Juda mazali",
  },
  {
    id: 7,
    title: "Popcorn",
    price: 21000,
    icon: "food.svg",
    count: 0,
    description: "Juda mazali",
  },
  {
    id: 8,
    title: "Coke",
    price: 5000,
    icon: "food.svg",
    count: 0,
    description: "Juda mazali",
  },
  {
    id: 9,
    title: "Cake",
    price: 20000,
    icon: "food.svg",
    count: 0,
    description: "Juda mazali",
  },
  {
    id: 10,
    title: "Icecream",
    price: 4000,
    icon: "food.svg",
    count: 0,
    description: "Juda mazali",
  },
  {
    id: 11,
    title: "Cookie",
    price: 2000,
    icon: "food.svg",
    count: 0,
    description: "Juda mazali",
  },
  {
    id: 12,
    title: "Flan",
    price: 7000,
    icon: "food.svg",
    count: 0,
    description: "Juda mazali",
  },
];
